## Практическое задание к уроку 1 по теме "Основные понятия и структуры PyTorch".

In [1]:
import torch

##### 1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.randn(size=(3, 4, 5))
a

tensor([[[-0.9033, -1.7295,  1.2303,  1.2671,  0.1603],
         [-1.4026, -0.9490,  2.7413,  0.5085,  1.0967],
         [ 0.0533,  0.6417, -0.0669,  1.3568,  0.9088],
         [-0.3913, -0.3560, -0.2816,  1.3446,  0.0215]],

        [[-2.1983, -0.7572,  1.8848, -0.1347,  0.2652],
         [-1.1139,  0.1164, -0.8734, -0.8587,  1.7656],
         [-0.2869, -0.6333, -1.3414, -0.7579, -0.4040],
         [ 0.9561, -0.7896,  1.3161,  0.5392,  2.3055]],

        [[-0.3733, -0.6290,  0.5379, -1.3508,  2.6497],
         [ 2.4726, -0.7064,  0.4209, -0.6317, -2.5613],
         [ 0.2260, -0.5206, -0.0827,  1.5797, -0.8916],
         [-1.1939,  0.4431,  0.3588,  0.0161, -0.0589]]])

##### 2. Выведите его форму (shape)

In [3]:
a.shape

torch.Size([3, 4, 5])

##### 3. Приведите его к форме 6х10

In [4]:
a = a.reshape(6, 10)
a

tensor([[-0.9033, -1.7295,  1.2303,  1.2671,  0.1603, -1.4026, -0.9490,  2.7413,
          0.5085,  1.0967],
        [ 0.0533,  0.6417, -0.0669,  1.3568,  0.9088, -0.3913, -0.3560, -0.2816,
          1.3446,  0.0215],
        [-2.1983, -0.7572,  1.8848, -0.1347,  0.2652, -1.1139,  0.1164, -0.8734,
         -0.8587,  1.7656],
        [-0.2869, -0.6333, -1.3414, -0.7579, -0.4040,  0.9561, -0.7896,  1.3161,
          0.5392,  2.3055],
        [-0.3733, -0.6290,  0.5379, -1.3508,  2.6497,  2.4726, -0.7064,  0.4209,
         -0.6317, -2.5613],
        [ 0.2260, -0.5206, -0.0827,  1.5797, -0.8916, -1.1939,  0.4431,  0.3588,
          0.0161, -0.0589]])

##### 4. Создайте случайный IntTensor размера 10

In [5]:
b = torch.randint(10, size=(10,)).int()
print(b)
print(b.type())

tensor([3, 3, 3, 0, 7, 2, 9, 0, 0, 0], dtype=torch.int32)
torch.IntTensor


##### 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [6]:
a * b

tensor([[-2.7098, -5.1886,  3.6910,  0.0000,  1.1219, -2.8052, -8.5414,  0.0000,
          0.0000,  0.0000],
        [ 0.1598,  1.9250, -0.2007,  0.0000,  6.3617, -0.7826, -3.2041, -0.0000,
          0.0000,  0.0000],
        [-6.5949, -2.2716,  5.6543, -0.0000,  1.8562, -2.2278,  1.0474, -0.0000,
         -0.0000,  0.0000],
        [-0.8608, -1.9000, -4.0243, -0.0000, -2.8279,  1.9123, -7.1061,  0.0000,
          0.0000,  0.0000],
        [-1.1199, -1.8871,  1.6136, -0.0000, 18.5480,  4.9452, -6.3577,  0.0000,
         -0.0000, -0.0000],
        [ 0.6781, -1.5617, -0.2480,  0.0000, -6.2412, -2.3879,  3.9879,  0.0000,
          0.0000, -0.0000]])

##### 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6  
Подсказка: .dot может не подойти

In [7]:
result = a @ a.T
print(result)
result.shape

tensor([[18.7962,  1.4467,  6.0433,  4.4976, -3.9742,  4.6345],
        [ 1.4467,  5.2533, -1.1471, -1.4164, -1.6231,  1.2454],
        [ 6.0433, -1.1471, 14.9184, -0.1219, -3.9886,  0.2426],
        [ 4.4976, -1.4164, -0.1219, 11.8960, -3.0325, -1.6077],
        [-3.9742, -1.6231, -3.9886, -3.0325, 23.4193, -7.2712],
        [ 4.6345,  1.2454,  0.2426, -1.6077, -7.2712,  5.3736]])


torch.Size([6, 6])

##### 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [8]:
xzt = torch.Tensor([1, 0.5, 2])
xzt.requires_grad = True
y = xzt[0]**3 + xzt[1] - 75 * xzt[2]

In [9]:
y.backward()
xzt.grad

tensor([  3.,   1., -75.])

##### 8. Создайте единичный тензор размера 5x6

In [10]:
c = torch.ones(5, 6)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

##### 9. Переведите его в формат numpy

In [11]:
c = c.numpy()
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)