## Практическое задание к уроку 1 по теме "Основные понятия и структуры PyTorch".

In [1]:
import torch

1. Создайте случайный FloatTensor размера 3x4x5

In [2]:
a = torch.randn(size=(3, 4, 5))
a

tensor([[[ 0.3976, -0.3392,  1.6806,  0.5407, -1.2124],
         [ 0.7525, -0.8717, -0.9450, -0.2268,  0.5566],
         [-1.0527, -0.5293,  0.2289,  0.3139, -0.6976],
         [ 0.7933, -0.3921, -1.7140,  0.2473, -0.2558]],

        [[-0.6319,  0.9490,  0.4840,  1.0570,  0.5634],
         [-1.3545,  0.8177,  0.3318,  0.6997,  0.2536],
         [ 0.1272,  0.6053, -1.3688,  2.0109,  0.4649],
         [ 1.3179,  0.2812, -0.7838, -0.3228, -0.9617]],

        [[-0.8108, -1.1340,  0.1305,  1.1224,  0.6196],
         [-0.9953, -0.6660,  0.1017,  0.2994,  1.0678],
         [ 3.1540, -1.4933,  0.7229,  0.1545,  0.1247],
         [ 0.1174,  0.5183,  0.8758, -1.3778, -0.1356]]])

2. Выведите его форму (shape)

In [3]:
a.shape

torch.Size([3, 4, 5])

3. Приведите его к форме 6х10

In [4]:
a = a.reshape(6, 10)
a

tensor([[ 0.3976, -0.3392,  1.6806,  0.5407, -1.2124,  0.7525, -0.8717, -0.9450,
         -0.2268,  0.5566],
        [-1.0527, -0.5293,  0.2289,  0.3139, -0.6976,  0.7933, -0.3921, -1.7140,
          0.2473, -0.2558],
        [-0.6319,  0.9490,  0.4840,  1.0570,  0.5634, -1.3545,  0.8177,  0.3318,
          0.6997,  0.2536],
        [ 0.1272,  0.6053, -1.3688,  2.0109,  0.4649,  1.3179,  0.2812, -0.7838,
         -0.3228, -0.9617],
        [-0.8108, -1.1340,  0.1305,  1.1224,  0.6196, -0.9953, -0.6660,  0.1017,
          0.2994,  1.0678],
        [ 3.1540, -1.4933,  0.7229,  0.1545,  0.1247,  0.1174,  0.5183,  0.8758,
         -1.3778, -0.1356]])

4. Создайте случайный IntTensor размера 10

In [5]:
b = torch.randint(10, size=(10,)).int()
print(b)
print(b.type())

tensor([2, 6, 9, 7, 1, 1, 9, 1, 8, 1], dtype=torch.int32)
torch.IntTensor


5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [6]:
a * b

tensor([[  0.7952,  -2.0353,  15.1256,   3.7849,  -1.2124,   0.7525,  -7.8455,
          -0.9450,  -1.8146,   0.5566],
        [ -2.1053,  -3.1759,   2.0601,   2.1976,  -0.6976,   0.7933,  -3.5290,
          -1.7140,   1.9781,  -0.2558],
        [ -1.2638,   5.6941,   4.3559,   7.3987,   0.5634,  -1.3545,   7.3592,
           0.3318,   5.5978,   0.2536],
        [  0.2544,   3.6317, -12.3188,  14.0760,   0.4649,   1.3179,   2.5311,
          -0.7838,  -2.5825,  -0.9617],
        [ -1.6217,  -6.8039,   1.1748,   7.8567,   0.6196,  -0.9953,  -5.9938,
           0.1017,   2.3950,   1.0678],
        [  6.3080,  -8.9600,   6.5064,   1.0816,   0.1247,   0.1174,   4.6650,
           0.8758, -11.0224,  -0.1356]])

6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6  
Подсказка: .dot может не подойти

In [7]:
result = a @ a.T
print(result)
result.shape

tensor([[ 7.4403,  3.5213, -1.9345, -0.9062,  0.3992,  1.9538],
        [ 3.5213,  5.8732, -1.6433,  1.9843,  0.5020, -4.3199],
        [-1.9345, -1.6433,  6.1359, -0.0660,  2.3523, -3.2697],
        [-0.9062,  1.9843, -0.0660,  9.9751, -1.1255, -0.9345],
        [ 0.3992,  0.5020,  2.3523, -1.1255,  6.2783, -1.4491],
        [ 1.9538, -4.3199, -3.2697, -0.9345, -1.4491, 15.7060]])


torch.Size([6, 6])

7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

Полная производная функции:  
$y' = \frac{\partial y}{\partial x} + \frac{\partial y}{\partial z} + \frac{\partial y}{\partial t}$  
<br>
Частные производные:  
$\frac{\partial y}{\partial x} = 3x^2$  
$\frac{\partial y}{\partial z} = 1$  
$\frac{\partial y}{\partial t} = -75$  
<br>
Тогда полная производная:  
$y' = 3x^2 + 1 - 75 = 3x^2 - 74$  
<br>
В точке (1, 0.5, 2) производная равна:  
$y' = 3 \cdot 1 - 74 = 3 - 74 = \underline{-71}$

8. Создайте единичный тензор размера 5x6

In [8]:
c = torch.ones(5, 6)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

9. Переведите его в формат numpy

In [9]:
c = c.numpy()
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)